#!/bin/bash
clear
figlet -f Thin Ip-Cam-Online
echo ""
echo ""
echo " |≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠|"
echo " |               ╭Author╮                 |"
echo " |               ╰MR.R24╯                 |"
echo " |Telegram : @Gantas                      |"
echo "[+]                                      [+]"
echo " |Gmail    :rezabodong123@gmail.com       |"
echo " |                                        |"
echo " |   F U C K - Y O U - R E C O D E E R    |"
echo " |                                        |"
echo " |≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠|"
echo ""
echo " [1] Indonesia"
echo " [2] Jepang"
echo " [3] Amerika"
echo " [4] Italy"
read -p "Masukan=>>>" pil ;

if [ $pil = 1 ] || [ $pil = 1 ]
then
clear
cd country
sh indo.sh
fi

if [ $pil = 2 ] || [ $pil = 2 ]
then
clear
cd country
sh jpn.sh
fi

if [ $pil = 3 ] || [ $pil = 3 ]
then
clear 
cd country
sh usa.sh
fi

if [ $pil = 4 ] || [ $pil = 4 ]
then
clear
cd country
sh ita.sh
fi
